[graph]
targets = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MPL-2.0",
    "GPL-2.0",
    "GPL-3.0",
    "LGPL-2.1",
    "Unicode-3.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Zlib",
    "ISC",
    "CC0-1.0",
]
